$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: amlv2-pj-generate-job-jsons
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
conda_file: generate_json_jobs-conda.yml