name: cd
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches: 
    - main
    paths:
      - scoring/**
      - #OTHERS!!!!?
      - .github/workflows/cd.yml
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPLE }} 

      - name: Install az ml & and tools
        run: |
          az extension add -n ml -y --version 2.6.1
          sudo apt install jq
          pip install yq
      
      - name: Run deployment
        uses: ./.github/actions/aml-endpoint-deploy
        with:
          resourceGroup: rg-dev-euwest-airesearch 
          workspaceName: aidevelopmentml 
          endpointFile: .././batch-endpoint.yml
          deploymentFile: .././scoring/batch-deployment.yml
          modelVersion: latest

   
      # WHy do we need to pass the resourcegroup etc, the fact that we connect to resource group through Service Principal?
      - name: Test deployment
        uses: ./.github/actions/aml-endpoint-test
        with:
          resourceGroup: rg-dev-euwest-airesearch 
          workspaceName: aidevelopmentml 
          endpointFile: .././batch-endpoint.yml
          requestFile: azureml://datastores/aidatalake_synapse/paths/EDWData/parallel-pipeline/amlv2_pj_evaluation_data/tenant_2603713.csv

  
     