name: ci
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
    - integration
    paths:
    - data-engineering/**
    - evaluation/**
    - training/**
    - .github/workflows/ci.yml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
      - name: Install az ml & set default values for AML
        run: |
          az extension add -n ml -y --version 2.6.1
          az configure --defaults group=trial workspace=mlws location=central
      - name:
        run: |
          AZURE_ML_CLI_PRIVATE_FEATURES_ENABLED=true az ml job create -f pipeline.yml
      - name: test one or two registered models to make sure things work?!!!
        uses: ./.github/actions/aml-endpoint-test
        with:
          resourceGroup: trial 
          workspaceName: mlws 
          endpointFile: scoring/batch-deployment.yaml
          requestFile: azureml://datastores/workspaceblobstore/paths/oj-score-data/store1085_tropicana.csv
      - name:  Create Pull Request to Main
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }} #setup: provide your github secret name
          head: ${{ github.ref }}
          base: main
          title: "An automatically created PR by successful CI to main"